"""Known execution_queue task types."""

TASK_NOTIFY_MANAGER = "notify_manager"
TASK_UPDATE_METRICS = "update_metrics"
TASK_AGGREGATE_METRICS = "aggregate_metrics"
TASK_PROCESS_KNOWLEDGE_UPLOAD = "process_knowledge_upload"
TASK_RETIGHTEN_KNOWLEDGE_DOCUMENT = "retighten_knowledge_document"
TASK_PUBLISH_KNOWLEDGE_READY_ANSWERS = "publish_knowledge_ready_answers"
TASK_RETRY_KNOWLEDGE_FAILED_BATCHES = "retry_knowledge_failed_batches"
TASK_RUN_FULL_RAG_EVAL = "run_full_rag_eval"

KNOWN_TASK_TYPES = {
    TASK_NOTIFY_MANAGER,
    TASK_UPDATE_METRICS,
    TASK_AGGREGATE_METRICS,
    TASK_PROCESS_KNOWLEDGE_UPLOAD,
    TASK_RETIGHTEN_KNOWLEDGE_DOCUMENT,
    TASK_PUBLISH_KNOWLEDGE_READY_ANSWERS,
    TASK_RETRY_KNOWLEDGE_FAILED_BATCHES,
    TASK_RUN_FULL_RAG_EVAL,
}
