from typing import Protocol, Any


class CachePort(Protocol):
    async def get(self, key: str) -> Any: ...
    async def incr(self, key: str) -> int: ...
    async def expire(self, key: str, seconds: int) -> Any: ...
    async def exists(self, key: str) -> Any: ...
    async def sadd(self, key: str, value: str) -> Any: ...
    async def set(self, key: str, value: str, ex: int | None = None) -> Any: ...
    async def setex(self, key: str, seconds: int, value: str) -> Any: ...
    async def scard(self, key: str) -> int: ...
    async def srem(self, key: str, value: str) -> Any: ...
    async def delete(self, key: str) -> Any: ...


class CacheFactoryPort(Protocol):
    async def __call__(self) -> CachePort: ...


class NullCache:
    async def get(self, key: str): return None
    async def incr(self, key: str): return 1
    async def expire(self, key: str, seconds: int): return None
    async def exists(self, key: str): return False
    async def sadd(self, key: str, value: str): return None
    async def set(self, key: str, value: str, ex: int | None = None): return None
    async def setex(self, key: str, seconds: int, value: str): return None
    async def scard(self, key: str): return 0
    async def srem(self, key: str, value: str): return None
    async def delete(self, key: str): return None
