from typing import Protocol, Any


class ProjectControlPort(Protocol):
    async def create_project_with_user_id(self, user_id: str, name: str) -> str: ...
    async def get_projects_for_user_view(self, user_id: str) -> list[Any]: ...
    async def add_project_member(self, project_id: str, user_id: str, role: str) -> None: ...
    async def get_project_members_view(self, project_id: str) -> list[Any]: ...
