from typing import Protocol, Any

from src.domain.project_plane.thread_views import ThreadWithProjectView


class ThreadReaderPort(Protocol):
    async def get_dialogs(self, *args: Any, **kwargs: Any) -> list[dict]: ...
    async def get_messages(self, thread_id: str, limit: int, offset: int) -> list[dict]: ...
    async def get_state_json(self, thread_id: str) -> dict | None: ...
    async def get_thread_with_project_view(self, thread_id: str) -> ThreadWithProjectView | None: ...


class ThreadWriterPort(Protocol):
    async def get_dialogs(self, *args: Any, **kwargs: Any) -> list[dict]: ...
