#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."

ENV_EXAMPLE=".env.test.example"
ENV_FILE=".env.test"

if [[ ! -f "$ENV_EXAMPLE" ]]; then
  echo "ERROR: $ENV_EXAMPLE is missing" >&2
  exit 1
fi

if [[ ! -f "$ENV_FILE" ]]; then
  cp "$ENV_EXAMPLE" "$ENV_FILE"
  echo "created $ENV_FILE from $ENV_EXAMPLE"
fi

required_keys=(
  ADMIN_API_TOKEN
  ADMIN_BOT_TOKEN
  ADMIN_CHAT_ID
  ADMIN_PROJECT_ID
  CANVAS_ENABLED
  DATABASE_URL
  EMBEDDING_EXECUTOR_MAX_WORKERS
  EMBEDDING_LOCAL_MODEL
  EMBEDDING_LOCAL_THREADS
  EMBEDDING_PROVIDER
  EMBEDDING_VECTOR_DIMENSIONS
  EVENT_STORE_ENABLED
  EVENT_TTL_DAYS
  FRONTEND_URL
  GROQ_API_KEY
  GROQ_API_KEY2
  GROQ_API_KEY3
  HF_MODEL_URL
  HF_TOKEN
  JINA_API_KEY
  JINA_EMBEDDING_BATCH_SIZE
  JINA_EMBEDDING_MODEL
  JINA_EMBEDDING_TIMEOUT_SECONDS
  JWT_SECRET_KEY
  KNOWLEDGE_EMBED_BATCH_SIZE
  OMP_NUM_THREADS
  PLATFORM_WEBHOOK_SECRET
  PRO_MODE_ENABLED
  RAG_EVAL_LLM_MIN_DELAY_SECONDS
  RATE_LIMIT_BURST
  RATE_LIMIT_REQUESTS_PER_MINUTE
  REDIS_URL
  RENDER_EXTERNAL_URL
  TOKENIZERS_PARALLELISM
  TOKEN_ENCRYPTION_KEY
  TOOL_HTTP_ALLOWED_DOMAINS
  TOOL_N8N_ALLOWED_WEBHOOKS
  VITE_API_URL
  VOYAGE_API_KEY
  VOYAGE_EMBEDDING_BATCH_SIZE
  VOYAGE_EMBEDDING_MODEL
  VOYAGE_EMBEDDING_OUTPUT_DIMENSIONS
  VOYAGE_EMBEDDING_TIMEOUT_SECONDS
  VOYAGE_EMBEDDING_URL
  WEB_CONCURRENCY
  WORKER_CONCURRENCY
)

missing=0

for key in "${required_keys[@]}"; do
  if ! grep -qE "^${key}=" "$ENV_EXAMPLE"; then
    echo "ERROR: $ENV_EXAMPLE misses $key" >&2
    missing=1
  fi

  if ! grep -qE "^${key}=" "$ENV_FILE"; then
    echo "ERROR: $ENV_FILE misses $key" >&2
    missing=1
  fi
done

if [[ "$missing" -ne 0 ]]; then
  exit 1
fi

echo "test env surface OK"
