"""Project role and channel-kind invariants for the control plane."""

PROJECT_OWNER = "owner"
PROJECT_ADMIN = "admin"
PROJECT_MANAGER = "manager"
PROJECT_VIEWER = "viewer"

ALLOWED_PROJECT_ROLES = {
    PROJECT_OWNER,
    PROJECT_ADMIN,
    PROJECT_MANAGER,
    PROJECT_VIEWER,
}

CHANNEL_PLATFORM = "platform"
CHANNEL_CLIENT = "client"
CHANNEL_MANAGER = "manager"
CHANNEL_WIDGET = "widget"

ALLOWED_CHANNEL_KINDS = {
    CHANNEL_PLATFORM,
    CHANNEL_CLIENT,
    CHANNEL_MANAGER,
    CHANNEL_WIDGET,
}

PROJECT_WRITE_ROLES = [PROJECT_OWNER, PROJECT_ADMIN]
PROJECT_READ_ROLES = [PROJECT_OWNER, PROJECT_ADMIN, PROJECT_MANAGER, PROJECT_VIEWER]
PROJECT_ADMIN_ROLES = [PROJECT_OWNER, PROJECT_ADMIN]
PROJECT_MANAGER_ROLES = [PROJECT_OWNER, PROJECT_ADMIN, PROJECT_MANAGER]
