"""
Generate OpenAPI artifacts from the FastAPI app without starting a server.

Outputs:
- openapi.json
- frontend/openapi.json

The TypeScript schema is generated by the npm workflow via openapi-typescript.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src.interfaces.http.app import app
BACKEND_OPENAPI = ROOT / "openapi.json"
FRONTEND_OPENAPI = ROOT / "frontend" / "openapi.json"


def write_schema(path: Path, schema: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(schema, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )


def main() -> None:
    schema = app.openapi()
    write_schema(BACKEND_OPENAPI, schema)
    write_schema(FRONTEND_OPENAPI, schema)
    print(f"Wrote {BACKEND_OPENAPI.relative_to(ROOT)}")
    print(f"Wrote {FRONTEND_OPENAPI.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
